# Generated by Django 2.1.5 on 2019-10-10 15:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('good_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=10)),
                ('problem_description', models.TextField()),
                ('adres', models.CharField(max_length=60)),
                ('file', models.FileField(null=True, upload_to='')),
                ('date_added', models.DateField(default=datetime.datetime.today)),
                ('status', models.CharField(choices=[(0, 'На рассмотрении'), (1, 'Рассмотрено'), (2, 'Выполнено')], default=0, max_length=30)),
                ('birthday', models.DateField(default=datetime.datetime.today)),
                ('type_needed_help', models.CharField(choices=[('Лечение', 'Лечение'), ('Интернет', 'Интернет'), ('Многодетная семья', 'Многодетная семья'), ('Животным', 'Животным'), ('Временно премещенные лица', 'Временно премещенные лица'), ('Дома пристарелых', 'Дома пристарелых'), ('Донорство', 'Донорство'), ('Другое', 'Другое')], default='Другое', max_length=30)),
            ],
            options={
                'verbose_name': 'Заявка физического лица',
                'verbose_name_plural': 'Заявки физических лиц',
            },
        ),
        migrations.CreateModel(
            name='NeedHelpPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=200)),
                ('full_description', models.TextField()),
                ('published_date', models.DateField(default=datetime.datetime.today)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('human_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='good_api.HumanRecord')),
            ],
            options={
                'verbose_name': 'Пост заявки помощи',
                'verbose_name_plural': 'Пост заявок помощи',
            },
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=200)),
                ('full_description', models.TextField()),
                ('published_date', models.DateField(default=datetime.datetime.today)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='OrganizationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=10)),
                ('problem_description', models.TextField()),
                ('adres', models.CharField(max_length=60)),
                ('file', models.FileField(null=True, upload_to='')),
                ('date_added', models.DateField(default=datetime.datetime.today)),
                ('status', models.CharField(choices=[(0, 'На рассмотрении'), (1, 'Рассмотрено'), (2, 'Выполнено')], default=0, max_length=30)),
                ('organization_name', models.CharField(max_length=60)),
                ('info_about_organization', models.CharField(max_length=200)),
                ('special_code', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Заявка юридического лица',
                'verbose_name_plural': 'Заявки юридических лиц',
            },
        ),
        migrations.CreateModel(
            name='ReportPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=200)),
                ('full_description', models.TextField()),
                ('published_date', models.DateField(default=datetime.datetime.today)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('human_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='good_api.HumanRecord')),
                ('organization_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='good_api.OrganizationRecord')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
            },
        ),
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=10, null=True)),
                ('linked_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='good_api.NeedHelpPost')),
            ],
            options={
                'verbose_name': 'Отозвавшийся',
                'verbose_name_plural': 'Отозвавшиеся',
            },
        ),
        migrations.DeleteModel(
            name='Individual',
        ),
        migrations.DeleteModel(
            name='LegalEntity',
        ),
        migrations.AddField(
            model_name='needhelppost',
            name='organization_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='good_api.OrganizationRecord'),
        ),
    ]
