# Generated by Django 2.2.5 on 2019-09-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodDeedRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=500, null=True)),
                ('typeHelpObj', models.CharField(choices=[('0', 'Частное лицо'), ('1', 'Организация')], default='1', max_length=20)),
                ('adress', models.CharField(max_length=100, null=True)),
                ('linkToWeb', models.CharField(max_length=100, null=True)),
                ('phoneNumber', models.CharField(max_length=10, null=True)),
                ('generalDescription', models.TextField(max_length=500, null=True)),
                ('status', models.CharField(choices=[('0', 'На рассмотрении'), ('1', 'Рассмотрено')], default='1', max_length=30)),
                ('creationDate', models.DateField()),
            ],
        ),
    ]
