# Generated by Django 2.0 on 2019-10-08 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoodDeedRecord',
        ),
    ]
