# Generated by Django 2.2.5 on 2019-10-09 08:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=10)),
                ('problem_description', models.TextField()),
                ('adress', models.CharField(max_length=60)),
                ('file', models.FileField(null=True, upload_to='')),
                ('date_added', models.DateField(default=datetime.datetime.today)),
                ('status', models.CharField(choices=[(0, 'На рассмотрении'), (1, 'Рассмотрено'), (2, 'Выполнено')], default=0, max_length=30)),
                ('birthday', models.DateField(default=datetime.datetime.today)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NeedHelpPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=200)),
                ('full_description', models.TextField()),
                ('published_date', models.DateField(default=datetime.datetime.today)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('human_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.HumanRecord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=200)),
                ('full_description', models.TextField()),
                ('published_date', models.DateField(default=datetime.datetime.today)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=10)),
                ('problem_description', models.TextField()),
                ('adress', models.CharField(max_length=60)),
                ('file', models.FileField(null=True, upload_to='')),
                ('date_added', models.DateField(default=datetime.datetime.today)),
                ('status', models.CharField(choices=[(0, 'На рассмотрении'), (1, 'Рассмотрено'), (2, 'Выполнено')], default=0, max_length=30)),
                ('organization_name', models.CharField(max_length=60)),
                ('info_about_organization', models.CharField(max_length=200)),
                ('special_code', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=200)),
                ('full_description', models.TextField()),
                ('published_date', models.DateField(default=datetime.datetime.today)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('human_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.HumanRecord')),
                ('organization_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.OrganizationRecord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=10, null=True)),
                ('linked_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.NeedHelpPost')),
            ],
        ),
        migrations.DeleteModel(
            name='GoodDeedRecord',
        ),
        migrations.AddField(
            model_name='needhelppost',
            name='organization_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.OrganizationRecord'),
        ),
    ]
