# Generated by Django 2.2.5 on 2019-10-09 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20191009_1125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='humanrecord',
            options={'verbose_name': 'Заявка физического лица', 'verbose_name_plural': 'Заявки физических лиц'},
        ),
        migrations.AlterModelOptions(
            name='needhelppost',
            options={'verbose_name': 'Пост заявки помощи', 'verbose_name_plural': 'Пост заявок помощи'},
        ),
        migrations.AlterModelOptions(
            name='newspost',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='organizationrecord',
            options={'verbose_name': 'Заявка юридического лица', 'verbose_name_plural': 'Заявки юридических лиц'},
        ),
        migrations.AlterModelOptions(
            name='reportpost',
            options={'verbose_name': 'Отчет', 'verbose_name_plural': 'Отчеты'},
        ),
        migrations.AlterModelOptions(
            name='respondent',
            options={'verbose_name': 'Отозвавшийся', 'verbose_name_plural': 'Отозвавшиеся'},
        ),
    ]
