# Generated by Django 2.2.5 on 2019-10-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20191009_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='humanrecord',
            name='type_needed_help',
            field=models.CharField(choices=[('Лечение', 'Лечение'), ('Интернет', 'Интернет'), ('Многодетная семья', 'Многодетная семья'), ('Животным', 'Животным'), ('Временно премещенные лица', 'Временно премещенные лица'), ('Дома пристарелых', 'Дома пристарелых'), ('Донорство', 'Донорство'), ('Другое', 'Другое')], default='Другое', max_length=30),
        ),
    ]
